version: "3.8"

services:
 
  tomcat:
   build: .
    #context: .
    #dockerfile: Dockerfile
   container_name: tomcat

   ports:
    - "8080:8080"
  #  environment:
  #   DB_HOST: mysql
  #   DB_PORT: 3306
  #   DB_NAME: accounts
  #   DB_USER: admin
  #   DB_PASS: admin123
  #   RABBIT_HOST: rabbitmq
  #   MEMCACHED_HOST: memcached 
################

      